# Generated by Django 2.2.5 on 2019-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191013_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='system',
            field=models.CharField(choices=[('m', 'Metric'), ('i', 'Imperial')], max_length=1, null=True),
        ),
    ]
