# Generated by Django 2.2.4 on 2020-03-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191223_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='system',
            field=models.CharField(choices=[('m', 'Metric'), ('i', 'Imperial')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
