version: '3.8'

services:
  wsgi:
    build: 
      context: ./backend/
      dockerfile: ../docker/wsgi/Dockerfile
    command: gunicorn sqtrex.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  asgi:
    build: 
      context: ./backend/
      dockerfile: ../docker/asgi/Dockerfile
    command: daphne --port 8001 --bind 0.0.0.0 sqtrex.asgi:application
    expose:
      - 8001
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  frontend:
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend/Dockerfile
    volumes:
      - frontend_data:/usr/src/app/dist/frontend
  nginx:
    build: ./docker/nginx
    volumes:
      - frontend_data:/usr/src/app/dist/frontend
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - frontend
      - wsgi
      - asgi
  redis:
    image: redis:6
    expose: 
      - 6379

volumes:
  postgres_data:
  frontend_data:
  media_volume:
