version: "3.8"

services:
  wsgi:
    build:
      context: ./backend/
      dockerfile: ../docker/django/Dockerfile
    command: gunicorn sqtrex.wsgi:application --log-file=- --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - media_volume:/home/app/web/media
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
  asgi:
    build:
      context: ./backend/
      dockerfile: ../docker/django/Dockerfile
    command: daphne --proxy-headers --port 8001 --bind 0.0.0.0 sqtrex.asgi:application
    expose:
      - 8001
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    restart: always
  huey:
    build:
      context: ./backend/
      dockerfile: ../docker/django/Dockerfile
    volumes:
      - media_volume:/home/app/web/media
    command: python manage.py run_huey
    env_file:
      - ./.env
    depends_on:
      - redis
    restart: always
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  frontend:
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend/Dockerfile
    volumes:
      - frontend_data:/usr/src/app/www/frontend
  nginx:
    build: ./docker/nginx
    volumes:
      - frontend_data:/usr/src/app/www/frontend
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - frontend
      - wsgi
      - asgi
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  redis:
    image: redis:6
    expose:
      - 6379
    restart: always

volumes:
  postgres_data:
  frontend_data:
  media_volume:
