#!/bin/bash

# usage: startdev [configurationangular] [backendhost:backendport] [backendsslport] [frontendhost]

trap killgroup SIGINT

killgroup(){
  echo killing...
  kill 0
}

./startdevbackend $2 $3 &
./startdevfrontend $4 $1 &
wait
