#!/bin/bash
source devsettings
source ../bin/activate

echo 'Starting backend'
echo 'Host/Port: '
echo ${1:-192.168.1.70:8000}
echo 'SSL host: '
echo ${2:-8443}

python backend/manage.py migrate

trap killgroup SIGINT

killgroup(){
  echo killing...
  kill 0
}

python backend/manage.py runserver ${1:-192.168.1.70:8000}  &
socat openssl-listen:${2:-8443},fork,reuseaddr,cert=backend/ssl/cert.pem,verify=0 tcp:${1:-192.168.1.70:8000} &
wait
