# Generated by Django 2.2.5 on 2019-10-19 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('utility', models.CharField(choices=[('b', 'Basic'), ('a', 'Auxiliary')], max_length=1, null=True)),
                ('mechanics', models.CharField(choices=[('c', 'Compound'), ('i', 'Isolated')], max_length=1, null=True)),
                ('force', models.CharField(choices=[('p', 'Pull'), ('h', 'Push')], max_length=1, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
