# Generated by Django 2.2.5 on 2019-10-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='utility',
        ),
        migrations.AddField(
            model_name='exercise',
            name='modality',
            field=models.CharField(choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='section',
            field=models.CharField(choices=[('u', 'Upper'), ('l', 'Lower'), ('c', 'Core')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='force',
            field=models.CharField(choices=[('p', 'Pull'), ('h', 'Push'), ('s', 'Static')], max_length=1, null=True),
        ),
    ]
