# Generated by Django 2.2.5 on 2019-10-19 21:38

from django.db import migrations
import csv
import os 

def insert_exercises(apps, schema_editor):
    Exercise = apps.get_model('workouts', 'Exercise')
    path = os.path.dirname(os.path.realpath(__file__)) + '/exercises.csv'
    with open(path) as f:
        reader = csv.reader(f)
        for row in reader:
            if row[6] == 'm':
                mechanics = 'c'
            else:
                mechanics = 'i'

            _, created = Exercise.objects.get_or_create(
                name=row[1],
                section=row[3],
                force=row[4],
                modality=row[5],
                mechanics=mechanics
            )


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20191019_2138'),
    ]

    operations = [
        migrations.RunPython(insert_exercises),
    ]
