# Generated by Django 2.2.5 on 2019-10-20 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0003_seed_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlanTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Enter the workout plan templates short name (ex: PPL, SS, SL)', max_length=200)),
                ('name', models.CharField(help_text='Enter the workout plan templates name (ex: Push Pull Legs, Starting Strength)', max_length=200)),
                ('description', models.TextField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanSessionTemplateSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('workout_plan_session_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.WorkoutPlanTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanSessionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the workout plan session templates name (ex: Push, Pull, Legs, Upper, Lower, A, B)', max_length=200)),
                ('workout_plan_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.WorkoutPlanTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanSessionExerciseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('number_of_sets', models.PositiveIntegerField()),
                ('number_of_repetitions', models.PositiveIntegerField()),
                ('number_of_repetitions_up_to', models.PositiveIntegerField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise')),
                ('workout_plan_session_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.WorkoutPlanSessionTemplate')),
            ],
        ),
    ]
