# Generated by Django 2.2.5 on 2019-10-20 14:56

from django.db import migrations

def insert_workout_templates(apps, schema_editor):
    Model = apps.get_model('workouts', 'WorkoutPlanTemplate')
    created_template, _ = Model.objects.get_or_create(
        short_name='SS',
        name='Starting Strength',
        description='Beginner''s strength program'
    )

    Session = apps.get_model('workouts', 'WorkoutPlanSessionTemplate')
    created_session, _ = Session.objects.get_or_create(
        name='A',
        workout_plan_template=created_template
    )

    Exercise = apps.get_model('workouts', 'Exercise')

    SessionExercise = apps.get_model('workouts', 'WorkoutPlanSessionExerciseTemplate')
    created_session_exercise, _ = SessionExercise.objects.get_or_create(
        order=1,
        exercise=Exercise.objects.get(pk=1),
        number_of_sets=3,
        number_of_repetitions=5,
        workout_plan_session_template=created_session
    )

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workoutplansessionexercisetemplate_workoutplansessiontemplate_workoutplansessiontemplateschedule_wor'),
    ]

    operations = [
        migrations.RunPython(insert_workout_templates),
    ]
