# Generated by Django 2.2.5 on 2019-10-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_seed_workout_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplansessiontemplateschedule',
            name='workout_plan_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.WorkoutPlanTemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutplansessiontemplateschedule',
            name='workout_plan_session_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.WorkoutPlanSessionTemplate'),
        ),
    ]
