# Generated by Django 2.2.5 on 2019-11-09 20:39
# ratio conversion field was changed between the last data migration, so we'll delete all
# records and recreate them

from django.db import migrations

def insert_units(apps, schema_editor):
    Unit = apps.get_model('workouts', 'Unit')
    Unit.objects.all().delete()

    kilogram, _ = Unit.objects.get_or_create(
        name='Kilogram',
        abbreviation='kg',
        system='m'
    )
    centimeter, _ = Unit.objects.get_or_create(
        name='Centimeter',
        abbreviation='cm',
        system='m'
    )
    pound, _ = Unit.objects.get_or_create(
        name='Pound',
        abbreviation='lb',
        system='i'
    )
    foot, _ = Unit.objects.get_or_create(
        name='Foot',
        abbreviation='ft',
        system='i'
    )

    insert_conversion(apps, schema_editor, kilogram, pound, 2.20462262)
    insert_conversion(apps, schema_editor, pound, kilogram, 0.45359237)
    insert_conversion(apps, schema_editor, foot, centimeter, 0.032808399)
    insert_conversion(apps, schema_editor, centimeter, foot, 30.48)


def insert_conversion(apps, schema_editor, from_unit, to_unit, ratio):
    UnitConversion = apps.get_model('workouts', 'UnitConversion')
    conversion, created = UnitConversion.objects.get_or_create(
        from_unit=from_unit,
        to_unit=to_unit,
        ratio=ratio
    )

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_auto_20191109_2037'),
    ]

    operations = [
        migrations.RunPython(insert_units),
    ]
