# Generated by Django 2.2.5 on 2019-11-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_auto_20191109_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanSessionExercise',
            new_name='PlanSessionGroupExercise',
        ),
    ]
