# Generated by Django 2.2.5 on 2019-11-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_auto_20191110_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanProgressionStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_increase', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('weight_increase', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('mechanics', models.CharField(choices=[('c', 'Compound'), ('i', 'Isolated')], max_length=1, null=True)),
                ('force', models.CharField(choices=[('p', 'Pull'), ('h', 'Push'), ('s', 'Static')], max_length=1, null=True)),
                ('modality', models.CharField(choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine')], max_length=1, null=True)),
                ('section', models.CharField(choices=[('u', 'Upper'), ('l', 'Lower'), ('c', 'Core')], max_length=1, null=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='workouts.Exercise')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='workouts.Plan')),
                ('plan_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='workouts.PlanSession')),
                ('plan_session_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='workouts.PlanSessionGroup')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Unit')),
            ],
        ),
    ]
