# Generated by Django 2.2.5 on 2019-11-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_auto_20191113_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='workouts.Workout')),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='workout',
        ),
        migrations.CreateModel(
            name='WorkoutWarmup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('number_of_repetitions', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Unit')),
                ('workout_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmups', to='workouts.WorkoutGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workoutset',
            name='workout_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.WorkoutGroup'),
            preserve_default=False,
        ),
    ]
