# Generated by Django 2.2.5 on 2019-11-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0020_auto_20191115_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='repetition_type',
            field=models.CharField(choices=[('s', 'Standard'), ('r', 'Range'), ('f', 'To Failure'), ('a', 'As Many Repetitions As Possible'), ('n', 'None')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='repetition_type',
            field=models.CharField(choices=[('s', 'Standard'), ('r', 'Range'), ('f', 'To Failure'), ('a', 'As Many Repetitions As Possible'), ('n', 'None')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupexercise',
            name='number_of_repetitions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupwarmup',
            name='number_of_repetitions',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
