# Generated by Django 2.2.5 on 2019-11-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0021_auto_20191115_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='plan_session_group_exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.PlanSessionGroupExercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='plan_session_group_warmup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.PlanSessionGroupWarmUp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='number_of_repetitions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='number_of_repetitions',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
