# Generated by Django 2.2.5 on 2019-11-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0030_auto_20191124_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingweight',
            name='user',
        ),
    ]
