# Generated by Django 2.2.5 on 2019-11-26 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0031_remove_workingweight_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='plan_session_group_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.PlanSessionGroupExercise'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='plan_session_group_warmup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.PlanSessionGroupWarmUp'),
        ),
        migrations.AlterField(
            model_name='workingweight',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_weights', to='workouts.Workout'),
        ),
    ]
