# Generated by Django 2.2.5 on 2019-11-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0033_auto_20191126_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutgroup',
            name='plan_session_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.PlanSessionGroup'),
        ),
    ]
