# Generated by Django 2.2.5 on 2019-11-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0034_workoutgroup_plan_session_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingweight',
            name='previous_unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='previous_unit', to='workouts.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingweight',
            name='previous_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
