# Generated by Django 2.2.5 on 2019-11-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0035_auto_20191127_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='working_weight_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='working_weight_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
