# Generated by Django 2.2.5 on 2019-11-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0036_auto_20191129_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='working_weight_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='working_weight_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
