# Generated by Django 2.2.5 on 2019-12-01 15:55
# DATA migration, uncomment operations to apply

from django.db import migrations

def update_units(apps, schema_editor):
    Unit = apps.get_model('workouts', 'Unit')

    kilogram = Unit.objects.get(name='Kilogram')
    centimeter = Unit.objects.get(name='Centimeter')
    pound = Unit.objects.get(name='Pound')
    foot = Unit.objects.get(name='Foot')

    kilogram.measurement_type = 'w'
    pound.measurement_type = 'w'
    centimeter.measurement_type = 'h'
    foot.measurement_type = 'h'

    kilogram.save()
    pound.save()
    centimeter.save()
    foot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0038_unit_measurement_type'),
    ]

    operations = [
        #migrations.RunPython(update_units),
    ]
