# Generated by Django 2.2.5 on 2019-12-19 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0041_auto_20191210_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBioData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('weight', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('body_fat_percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('water_weight_percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('muscle_mass_percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('notes', models.TextField(null=True)),
                ('bone_mass_weight_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bone_mass_weight_unit', to='workouts.Unit')),
                ('height_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='height_unit', to='workouts.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weight_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_unit', to='workouts.Unit')),
            ],
        ),
    ]
