# Generated by Django 2.2.5 on 2019-12-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0042_userbiodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbiodata',
            name='bone_mass_weight',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
