# Generated by Django 2.2.4 on 2020-02-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0044_auto_20191221_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('p', 'In progress'), ('f', 'Finished')], default='p', max_length=1),
        ),
    ]
