# Generated by Django 3.0.2 on 2020-03-02 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0046_auto_20200225_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='user_submitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
