# Generated by Django 2.2.4 on 2020-03-08 16:25

from django.db import migrations

def update_push(apps, schema_editor):
    exercise = apps.get_model('workouts', 'Exercise')

    exercise.objects.filter(force='h').update(force='q')

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0048_auto_20200302_1744'),
    ]

    operations = [
        #migrations.RunPython(update_push),
    ]
