# Generated by Django 2.2.4 on 2020-03-18 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0052_auto_20200316_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='website',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.Plan'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='plan_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.PlanSession'),
        ),
    ]
