# Generated by Django 3.0.5 on 2020-05-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0054_exercise_muscle'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('a', 'Advanced')], max_length=1, null=True),
        ),
    ]
