# Generated by Django 3.0.5 on 2020-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0055_exercise_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingweight',
            name='manually_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced')], max_length=1, null=True),
        ),
    ]
