# Generated by Django 3.0.5 on 2020-06-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsetposition',
            name='accuracy',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsetposition',
            name='altitude',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsetposition',
            name='heading',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsetposition',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsetposition',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsetposition',
            name='speed',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmupposition',
            name='accuracy',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmupposition',
            name='altitude',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmupposition',
            name='heading',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmupposition',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmupposition',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmupposition',
            name='speed',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
    ]
