# Generated by Django 3.0.5 on 2020-06-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20200622_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabolicEquivalentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('met', models.DecimalField(decimal_places=2, max_digits=4)),
                ('from_value', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('to_value', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('weight_unit', models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph')], null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise')),
            ],
        ),
    ]
