# Generated by Django 2.2.5 on 2019-11-02 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0006_auto_20191020_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the workout plan session templates name (ex: Push, Pull, Legs, Upper, Lower, A, B)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSessionExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('number_of_sets', models.PositiveIntegerField()),
                ('number_of_repetitions', models.PositiveIntegerField()),
                ('number_of_repetitions_up_to', models.PositiveIntegerField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise')),
                ('plan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.PlanSession')),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutplansessiontemplate',
            name='workout_plan_template',
        ),
        migrations.RemoveField(
            model_name='workoutplansessiontemplateschedule',
            name='workout_plan_session_template',
        ),
        migrations.RemoveField(
            model_name='workoutplansessiontemplateschedule',
            name='workout_plan_template',
        ),
        migrations.RenameModel(
            old_name='WorkoutPlanTemplate',
            new_name='Plan',
        ),
        migrations.DeleteModel(
            name='WorkoutPlanSessionExerciseTemplate',
        ),
        migrations.DeleteModel(
            name='WorkoutPlanSessionTemplate',
        ),
        migrations.DeleteModel(
            name='WorkoutPlanSessionTemplateSchedule',
        ),
        migrations.AddField(
            model_name='plansession',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.Plan'),
        ),
    ]
