# Generated by Django 3.0.5 on 2020-06-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20200627_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='metabolicequivalenttask',
            name='exercise_type',
            field=models.CharField(choices=[('c', 'Cardio'), ('s', 'Strength')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metabolicequivalenttask',
            name='force',
            field=models.CharField(choices=[('p', 'Pull'), ('q', 'Push'), ('s', 'Static')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='metabolicequivalenttask',
            name='mechanics',
            field=models.CharField(choices=[('c', 'Compound'), ('i', 'Isolated')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='metabolicequivalenttask',
            name='modality',
            field=models.CharField(choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='metabolicequivalenttask',
            name='section',
            field=models.CharField(choices=[('u', 'Upper'), ('l', 'Lower'), ('c', 'Core')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise'),
        ),
    ]
