# Generated by Django 3.0.5 on 2020-06-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20200628_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='exercise_type',
            field=models.CharField(choices=[('c', 'Cardio'), ('s', 'Strength')], max_length=1, null=True),
        ),
    ]
