# Generated by Django 3.0.5 on 2020-06-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20200628_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='modality',
            field=models.CharField(choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine'), ('x', 'Calisthenics')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='modality',
            field=models.CharField(choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine'), ('x', 'Calisthenics')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='planprogressionstrategy',
            name='modality',
            field=models.CharField(choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine'), ('x', 'Calisthenics')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupprogressionstrategy',
            name='modality',
            field=models.CharField(choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine'), ('x', 'Calisthenics')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='plansessionprogressionstrategy',
            name='modality',
            field=models.CharField(choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine'), ('x', 'Calisthenics')], max_length=1, null=True),
        ),
    ]
