# Generated by Django 3.0.5 on 2020-06-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_auto_20200629_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise'),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('c', 'Cardio'), ('s', 'Strength')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='force',
            field=models.CharField(blank=True, choices=[('p', 'Pull'), ('q', 'Push'), ('s', 'Static')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='from_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='mechanics',
            field=models.CharField(blank=True, choices=[('c', 'Compound'), ('i', 'Isolated')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='modality',
            field=models.CharField(blank=True, choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine'), ('x', 'Calisthenics')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='section',
            field=models.CharField(blank=True, choices=[('u', 'Upper'), ('l', 'Lower'), ('c', 'Core')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='to_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph')], null=True),
        ),
    ]
