# Generated by Django 3.0.5 on 2020-06-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_auto_20200629_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
