# Generated by Django 3.0.5 on 2020-06-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_auto_20200630_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='met',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.MetabolicEquivalentTask'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='met_set_by_user',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='met',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.MetabolicEquivalentTask'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='met_set_by_user',
            field=models.BooleanField(null=True),
        ),
    ]
