# Generated by Django 2.2.5 on 2019-11-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_auto_20191109_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSessionGroupWarmUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('number_of_sets', models.PositiveIntegerField()),
                ('number_of_repetitions', models.PositiveIntegerField()),
                ('number_of_repetitions_up_to', models.PositiveIntegerField(null=True)),
                ('working_weight_percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('is_warmup', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise')),
                ('plan_session_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmups', to='workouts.PlanSessionGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
