# Generated by Django 3.0.5 on 2020-07-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_auto_20200701_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
