# Generated by Django 2.2.5 on 2019-11-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_planprogressionstrategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planprogressionstrategy',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='workouts.Plan'),
        ),
    ]
