# Generated by Django 3.0.5 on 2020-07-09 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_auto_20200702_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutWarmUpTimeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('workout_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='workouts.WorkoutWarmUp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutSetTimeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('workout_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='workouts.WorkoutSet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
