# Generated by Django 3.0.5 on 2020-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_auto_20200710_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='metabolicequivalenttask',
            name='can_be_automatically_selected',
            field=models.BooleanField(default=False),
        ),
    ]
