# Generated by Django 3.0.5 on 2020-07-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0019_remove_plan_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsetposition',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='workoutsetposition',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='workoutsetposition',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='workoutsetposition',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='workoutwarmupposition',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='workoutwarmupposition',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='workoutwarmupposition',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='workoutwarmupposition',
            name='timestamp',
        ),
    ]
