# Generated by Django 2.2.5 on 2019-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0019_auto_20191113_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='planprogressionstrategy',
            name='progression_type',
            field=models.CharField(choices=[('e', 'By Exercise'), ('c', 'By Characteristics')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupprogressionstrategy',
            name='progression_type',
            field=models.CharField(choices=[('e', 'By Exercise'), ('c', 'By Characteristics')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessionprogressionstrategy',
            name='progression_type',
            field=models.CharField(choices=[('e', 'By Exercise'), ('c', 'By Characteristics')], max_length=1, null=True),
        ),
    ]
