# Generated by Django 2.2.5 on 2019-11-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0023_auto_20191115_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Plan'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
