# Generated by Django 3.0.5 on 2020-07-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0023_auto_20200720_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='force',
            field=models.CharField(choices=[('p', 'Pull'), ('q', 'Push'), ('s', 'Static'), ('x', 'Pull and push')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='force',
            field=models.CharField(blank=True, choices=[('p', 'Pull'), ('q', 'Push'), ('s', 'Static'), ('x', 'Pull and push')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='planprogressionstrategy',
            name='force',
            field=models.CharField(choices=[('p', 'Pull'), ('q', 'Push'), ('s', 'Static'), ('x', 'Pull and push')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupprogressionstrategy',
            name='force',
            field=models.CharField(choices=[('p', 'Pull'), ('q', 'Push'), ('s', 'Static'), ('x', 'Pull and push')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='plansessionprogressionstrategy',
            name='force',
            field=models.CharField(choices=[('p', 'Pull'), ('q', 'Push'), ('s', 'Static'), ('x', 'Pull and push')], max_length=1, null=True),
        ),
    ]
