# Generated by Django 2.2.5 on 2019-11-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0024_auto_20191115_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutset',
            name='plan_session_group_exercise',
        ),
        migrations.RemoveField(
            model_name='workoutwarmup',
            name='plan_session_group_warmup',
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_number_of_repetitions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_number_of_repetitions_up_to',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='repetition_type',
            field=models.CharField(choices=[('s', 'Standard'), ('r', 'Range'), ('f', 'To Failure'), ('a', 'As Many Repetitions As Possible'), ('n', 'None')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_number_of_repetitions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_number_of_repetitions_up_to',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='repetition_type',
            field=models.CharField(choices=[('s', 'Standard'), ('r', 'Range'), ('f', 'To Failure'), ('a', 'As Many Repetitions As Possible'), ('n', 'None')], max_length=1, null=True),
        ),
    ]
