# Generated by Django 2.2.5 on 2019-11-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0025_auto_20191115_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='parent_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
