# Generated by Django 3.0.5 on 2020-09-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0028_userbiodata_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbiodata',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbiodata',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
