# Generated by Django 2.2.5 on 2019-11-24 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0029_auto_20191119_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingweight',
            name='date',
        ),
        migrations.AddField(
            model_name='workingweight',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.Workout'),
            preserve_default=False,
        ),
    ]
