# Generated by Django 3.0.5 on 2020-09-20 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0030_userbiodata_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='adoption_users',
            field=models.ManyToManyField(blank=True, related_name='plan_adoption_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
