# Generated by Django 3.0.5 on 2020-09-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0031_plan_adoption_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='energy_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], default=15),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='energy_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], default=15),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='energy_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], default=15),
        ),
        migrations.AlterField(
            model_name='metabolicequivalenttask',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='planprogressionstrategy',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupexercise',
            name='distance_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupexercise',
            name='speed_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupexercise',
            name='time_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupprogressionstrategy',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupwarmup',
            name='distance_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupwarmup',
            name='speed_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupwarmup',
            name='time_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='plansessionprogressionstrategy',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='userbiodata',
            name='bone_mass_weight_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='userbiodata',
            name='height_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='userbiodata',
            name='weight_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workingparameter',
            name='previous_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workingparameter',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='distance_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='plan_distance_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='plan_speed_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='plan_time_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='plan_weight_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='speed_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='time_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='distance_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='plan_distance_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='plan_speed_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='plan_time_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='plan_weight_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='speed_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='time_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='weight_unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
    ]
