# Generated by Django 3.0.5 on 2020-10-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0032_auto_20200925_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('a', 'Agonist'), ('n', 'Antagonist'), ('s', 'Synergist'), ('f', 'Fixator'), ('t', 'Target'), ('d', 'Dynamic stabilizer'), ('z', 'Antagonist stabilizer')], max_length=1)),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Muscle')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(blank=True, related_name='muscle_exercises', to='workouts.MuscleExercise'),
        ),
    ]
