# Generated by Django 3.0.5 on 2020-10-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0033_auto_20201001_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscles',
        ),
        migrations.AddField(
            model_name='muscleexercise',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='workouts.Exercise'),
            preserve_default=False,
        ),
    ]
