# Generated by Django 3.0.5 on 2021-01-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0037_auto_20210109_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillexercise',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('c', 'Cardio'), ('s', 'Strength')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='skillexercise',
            name='mechanics',
            field=models.CharField(choices=[('c', 'Compound'), ('i', 'Isolated')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='skillexercise',
            name='modality',
            field=models.CharField(choices=[('f', 'Free weights'), ('c', 'Cable'), ('m', 'Machine'), ('x', 'Calisthenics')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='skillexercise',
            name='parameter_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skillexercise',
            name='parameter_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skillexercise',
            name='parameter_type',
            field=models.CharField(choices=[('d', 'Distance'), ('r', 'Repetitions'), ('s', 'Speed')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='skillexercise',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Pound'), (3, 'Centimeter'), (4, 'Feet'), (5, 'Kilometer'), (6, 'Mile'), (7, 'Minute'), (8, 'Meter'), (9, 'Second'), (10, 'Yard'), (11, 'Kmh'), (12, 'Mph'), (13, 'Millisecond'), (14, 'Hour'), (15, 'Kcal'), (16, 'Kjoules')], null=True),
        ),
        migrations.AlterField(
            model_name='skillexercise',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workouts.Exercise'),
        ),
    ]
