# Generated by Django 2.2.5 on 2019-12-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0037_auto_20191130_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='measurement_type',
            field=models.CharField(choices=[('w', 'Weight'), ('h', 'Height')], max_length=1, null=True),
        ),
    ]
