# Generated by Django 2.2.5 on 2019-12-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0038_unit_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
