# Generated by Django 2.2.5 on 2019-12-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0040_auto_20191207_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingweight',
            name='previous_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_unit', to='workouts.Unit'),
        ),
        migrations.AlterField(
            model_name='workingweight',
            name='previous_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workingweight',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Unit'),
        ),
        migrations.AlterField(
            model_name='workingweight',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
