# Generated by Django 3.0.5 on 2021-01-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0040_auto_20210110_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='experience_next_level',
        ),
    ]
