# Generated by Django 3.0.5 on 2021-01-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0041_remove_userskill_experience_next_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='experience',
        ),
    ]
