# Generated by Django 3.0.5 on 2021-01-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0042_remove_userskill_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='experience',
            field=models.IntegerField(default=1000),
        ),
    ]
