# Generated by Django 2.2.4 on 2020-02-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0045_workout_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='owner',
            new_name='user',
        ),
    ]
