# Generated by Django 3.0.5 on 2021-02-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0047_auto_20210208_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyleaderboardposition',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='weeklyleaderboardposition',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='yearlyleaderboardposition',
            name='rank',
        ),
    ]
