# Generated by Django 3.0.2 on 2020-03-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0047_auto_20200302_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingweight',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Exercise'),
        ),
    ]
