# Generated by Django 2.2.4 on 2020-03-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0050_auto_20200310_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitConversion',
        ),
    ]
