# Generated by Django 3.0.5 on 2021-02-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0051_workout_in_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='skill_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.SkillExercise'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='skill_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.SkillExercise'),
        ),
    ]
