# Generated by Django 3.0.5 on 2021-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0052_auto_20210213_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
