# Generated by Django 3.0.5 on 2020-05-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0053_auto_20200318_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
