# Generated by Django 3.0.5 on 2021-05-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0054_auto_20210513_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plansessiongroupexercise',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='plansessiongroupwarmup',
            options={'ordering': ['order']},
        ),
    ]
