# Generated by Django 3.0.5 on 2021-05-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0055_auto_20210513_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutgroup',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='workoutset',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='workoutwarmup',
            options={'ordering': ['order']},
        ),
    ]
