# Generated by Django 3.0.5 on 2020-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0057_exercise_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='short_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
