# Generated by Django 3.0.5 on 2020-06-01 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0058_auto_20200521_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
