# Generated by Django 3.0.5 on 2020-06-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0059_exercise_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
