# Generated by Django 3.0.5 on 2020-06-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0060_auto_20200602_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
