# Generated by Django 3.0.5 on 2020-06-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0061_auto_20200602_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('c', 'Cardio'), ('s', 'Strength')], default='s', max_length=1),
            preserve_default=False,
        ),
    ]
