# Generated by Django 3.0.5 on 2020-06-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0062_exercise_exercise_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time')], max_length=1, null=True)),
                ('parameter_value', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('previous_parameter_value', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('manually_changed', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Exercise')),
                ('previous_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_unit', to='workouts.Unit')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Unit')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_parameters', to='workouts.Workout')),
            ],
        ),
        migrations.RenameField(
            model_name='plansessiongroupexercise',
            old_name='working_weight_percentage',
            new_name='working_parameter_percentage',
        ),
        migrations.RenameField(
            model_name='plansessiongroupwarmup',
            old_name='working_weight_percentage',
            new_name='working_parameter_percentage',
        ),
        migrations.RenameField(
            model_name='workoutset',
            old_name='working_weight_percentage',
            new_name='working_parameter_percentage',
        ),
        migrations.RenameField(
            model_name='workoutwarmup',
            old_name='working_weight_percentage',
            new_name='working_parameter_percentage',
        ),
        migrations.DeleteModel(
            name='WorkingWeight',
        ),
    ]
