# Generated by Django 3.0.5 on 2020-06-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0063_auto_20200604_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingparameter',
            name='parameter',
        ),
    ]
