# Generated by Django 3.0.5 on 2020-06-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0065_auto_20200604_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='planprogressionstrategy',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupprogressionstrategy',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessionprogressionstrategy',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time')], max_length=1, null=True),
        ),
    ]
