# Generated by Django 3.0.5 on 2020-06-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0066_auto_20200604_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planprogressionstrategy',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time')], default='w', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plansessiongroupprogressionstrategy',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time')], default='w', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plansessionprogressionstrategy',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time')], default='w', max_length=1),
            preserve_default=False,
        ),
    ]
