# Generated by Django 3.0.5 on 2020-06-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0067_auto_20200604_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='measurement_type',
            field=models.CharField(choices=[('w', 'Weight'), ('h', 'Height'), ('d', 'Distance'), ('t', 'Time')], max_length=1, null=True),
        ),
    ]
