# Generated by Django 3.0.5 on 2020-06-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0068_auto_20200606_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutset',
            old_name='working_parameter_percentage',
            new_name='working_weight_percentage',
        ),
        migrations.RenameField(
            model_name='workoutwarmup',
            old_name='working_parameter_percentage',
            new_name='working_weight_percentage',
        ),
        migrations.RemoveField(
            model_name='plansessiongroupexercise',
            name='working_parameter_percentage',
        ),
        migrations.RemoveField(
            model_name='plansessiongroupwarmup',
            name='working_parameter_percentage',
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='distance',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='distance_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('p', 'Parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='distance_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_distance_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='distance_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='speed',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='speed_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('a', 'As Fast as Possible'), ('p', 'Use working parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='speed_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_speed_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='speed_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='time',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='time_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('p', 'Parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='time_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_time_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='time_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='vo2max',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='vo2max_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='vo2max_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='working_distance_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='working_time_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='working_weight_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='distance',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='distance_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('p', 'Parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='distance_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warmup_distance_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='distance_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='speed',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='speed_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('a', 'As Fast as Possible'), ('p', 'Use working parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='speed_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warmup_speed_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='speed_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='time',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='time_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('p', 'Parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='time_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warmup_time_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='time_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='vo2max',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='vo2max_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='vo2max_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='working_distance_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='working_time_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='working_weight_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupexercise',
            name='repetition_type',
            field=models.CharField(choices=[('s', 'Standard'), ('r', 'Range'), ('f', 'To Failure'), ('a', 'As Many Repetitions as Possible'), ('n', 'None')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='plansessiongroupwarmup',
            name='repetition_type',
            field=models.CharField(choices=[('s', 'Standard'), ('r', 'Range'), ('f', 'To Failure'), ('a', 'As Many Repetitions as Possible'), ('n', 'None')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='repetition_type',
            field=models.CharField(choices=[('s', 'Standard'), ('r', 'Range'), ('f', 'To Failure'), ('a', 'As Many Repetitions as Possible'), ('n', 'None')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='workoutwarmup',
            name='repetition_type',
            field=models.CharField(choices=[('s', 'Standard'), ('r', 'Range'), ('f', 'To Failure'), ('a', 'As Many Repetitions as Possible'), ('n', 'None')], max_length=1, null=True),
        ),
    ]
