# Generated by Django 3.0.5 on 2020-06-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0069_auto_20200606_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansessiongroupexercise',
            name='working_speed_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plansessiongroupwarmup',
            name='working_speed_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='planprogressionstrategy',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time'), ('s', 'Speed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='plansessiongroupprogressionstrategy',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time'), ('s', 'Speed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='plansessionprogressionstrategy',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time'), ('s', 'Speed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='measurement_type',
            field=models.CharField(choices=[('w', 'Weight'), ('h', 'Height'), ('d', 'Distance'), ('t', 'Time'), ('s', 'Speed')], max_length=1, null=True),
        ),
    ]
