# Generated by Django 3.0.5 on 2020-06-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0070_auto_20200606_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='distance',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='distance_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('p', 'Parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_distance',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_distance_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_speed',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_speed_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_time',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_time_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_vo2max',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_vo2max_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='speed',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='speed_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('a', 'As Fast as Possible'), ('p', 'Use working parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='time',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='time_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('p', 'Parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='vo2max',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='vo2max_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='working_distance_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='working_speed_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='working_time_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='distance',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='distance_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('p', 'Parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_distance',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_distance_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_speed',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_speed_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_time',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_time_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_vo2max',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_vo2max_up_to',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='speed',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='speed_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('a', 'As Fast as Possible'), ('p', 'Use working parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='time',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='time_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range'), ('p', 'Parameter')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='vo2max',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='vo2max_type',
            field=models.CharField(choices=[('n', 'None'), ('s', 'Standard'), ('r', 'Range')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='working_distance_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='working_speed_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='working_time_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
