# Generated by Django 3.0.5 on 2020-06-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0071_auto_20200607_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='distance_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_distance_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='speed_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_speed_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='time_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_time_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='distance_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_warmup_distance_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='speed_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_warmup_speed_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='time_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_warmup_time_unit', to='workouts.Unit'),
        ),
    ]
