# Generated by Django 3.0.5 on 2020-06-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0072_auto_20200607_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingparameter',
            name='parameter_type',
            field=models.CharField(choices=[('w', 'Weight'), ('d', 'Distance'), ('t', 'Time'), ('s', 'Speed')], default='w', max_length=1),
            preserve_default=False,
        ),
    ]
