# Generated by Django 3.0.5 on 2020-06-10 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0073_workingparameter_parameter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='plan_distance_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_plan_distance_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='plan_speed_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_plan_speed_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='plan_time_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_plan_time_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='plan_distance_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_warmup_plan_distance_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='plan_speed_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_warmup_plan_speed_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='plan_time_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_warmup_plan_time_unit', to='workouts.Unit'),
        ),
    ]
