# Generated by Django 3.0.5 on 2020-06-10 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0074_auto_20200610_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutset',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='workoutwarmup',
            name='unit',
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='plan_weight_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_plan_weight_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='weight_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_weight_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='expected_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='plan_weight_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_warmup_plan_weight_unit', to='workouts.Unit'),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='weight_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_warmup_weight_unit', to='workouts.Unit'),
        ),
    ]
