# Generated by Django 3.0.5 on 2020-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0076_auto_20200610_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='short_name',
            field=models.CharField(blank=True, help_text='Enter the workout plan templates short name (ex: PPL, SS, SL)', max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='website',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
