# Generated by Django 3.0.5 on 2020-06-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0077_auto_20200610_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractActivityPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('altitude', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('heading', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('speed', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('timestamp', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workoutset',
            name='tracking',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='workoutwarmup',
            name='tracking',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='WorkoutWarmUpPosition',
            fields=[
                ('abstractactivityposition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.AbstractActivityPosition')),
                ('workout_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.WorkoutWarmUp')),
            ],
            bases=('workouts.abstractactivityposition',),
        ),
        migrations.CreateModel(
            name='WorkoutSetPosition',
            fields=[
                ('abstractactivityposition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.AbstractActivityPosition')),
                ('workout_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.WorkoutSet')),
            ],
            bases=('workouts.abstractactivityposition',),
        ),
    ]
