# Generated by Django 2.2.4 on 2020-01-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='user',
        ),
    ]
