# Generated by Django 3.0.2 on 2020-02-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_target_object_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
