# Generated by Django 3.0.5 on 2020-07-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200621_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
