# Generated by Django 3.0.5 on 2020-07-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_message_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
