# Generated by Django 3.0.5 on 2020-07-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_visibilitygroup_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visibilitygroup',
            name='code',
            field=models.CharField(max_length=1),
        ),
    ]
