# Generated by Django 3.0.5 on 2020-07-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200729_0322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisibilityGroup',
        ),
    ]
