# Generated by Django 3.0.5 on 2020-08-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_delete_visibilitygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
