# Generated by Django 3.0.2 on 2020-02-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20200205_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_date',
            field=models.DateTimeField(null=True),
        ),
    ]
