# Generated by Django 3.0.5 on 2020-08-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='social.Post'),
            preserve_default=False,
        ),
    ]
