# Generated by Django 3.0.5 on 2020-09-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0030_userbiodata_visibility'),
        ('social', '0016_auto_20200904_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target_user_bio_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_target_user_bio_data', to='workouts.UserBioData'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='action_object_user_bio_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object_user_bio_data', to='workouts.UserBioData'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='target_user_bio_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_user_bio_data', to='workouts.UserBioData'),
        ),
    ]
