# Generated by Django 3.0.5 on 2020-10-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_auto_20200918_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited_date',
            field=models.DateTimeField(null=True),
        ),
    ]
