# Generated by Django 3.0.5 on 2020-10-09 21:18

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_message_edited_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
