# Generated by Django 3.0.5 on 2020-10-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
        ('social', '0019_auto_20201009_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_target_feature', to='development.Feature'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='action_object_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object_feature', to='development.Feature'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='target_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_feature', to='development.Feature'),
        ),
    ]
