# Generated by Django 3.0.5 on 2020-10-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0009_auto_20201030_1703'),
        ('social', '0020_auto_20201022_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_target_release', to='development.Release'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='action_object_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object_release', to='development.Release'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='target_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_release', to='development.Release'),
        ),
    ]
