# Generated by Django 3.0.5 on 2021-04-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_auto_20210425_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='target_user_bio_data',
        ),
    ]
