# Generated by Django 3.0.5 on 2020-10-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='state',
            field=models.CharField(choices=[('o', 'Open'), ('v', 'Up for voting'), ('p', 'In progress'), ('d', 'Done'), ('c', 'Closed')], default='o', max_length=1),
        ),
    ]
