# Generated by Django 3.0.5 on 2020-10-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_feature_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('state', models.CharField(choices=[('p', 'In progress'), ('d', 'Done')], default='p', max_length=1)),
                ('features', models.ManyToManyField(blank=True, related_name='release_features', to='development.Feature')),
            ],
        ),
    ]
