# Generated by Django 3.0.5 on 2020-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0003_auto_20201029_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='state',
            field=models.CharField(choices=[('v', 'Up for voting'), ('p', 'In progress'), ('d', 'Done')], default='p', max_length=1),
        ),
    ]
