# Generated by Django 3.0.5 on 2020-10-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0004_auto_20201029_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='text',
            new_name='description',
        ),
    ]
