# Generated by Django 3.0.5 on 2020-10-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0005_auto_20201029_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='features',
        ),
        migrations.AddField(
            model_name='feature',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='development.Release'),
        ),
    ]
