# Generated by Django 3.0.5 on 2020-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0006_auto_20201029_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
