# Generated by Django 3.0.5 on 2020-10-30 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('development', '0008_auto_20201030_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='release',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='release',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_release', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
