# Generated by Django 3.0.5 on 2020-10-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0009_auto_20201030_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='start',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='end',
            new_name='deploy_date',
        ),
    ]
