# Generated by Django 3.0.5 on 2020-12-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0010_auto_20201030_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='votes',
        ),
    ]
