# Generated by Django 3.0.5 on 2020-12-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0011_remove_feature_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='state',
            field=models.CharField(choices=[('o', 'Open'), ('p', 'In progress'), ('d', 'Done'), ('c', 'Closed')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='release',
            name='state',
            field=models.CharField(choices=[('p', 'In progress'), ('d', 'Done')], default='p', max_length=1),
        ),
    ]
