# Generated by Django 3.0.5 on 2021-01-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0012_auto_20201230_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='development.Release'),
        ),
    ]
