# Generated by Django 3.0.5 on 2020-07-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_visibility_workouts',
            field=models.CharField(choices=[('e', 'Everyone'), ('r', 'Registered users'), ('f', 'Followers'), ('u', 'Own user')], default='e', max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_visibility',
            field=models.CharField(choices=[('e', 'Everyone'), ('r', 'Registered users'), ('f', 'Followers'), ('u', 'Own user')], default='e', max_length=1),
        ),
    ]
