# Generated by Django 2.2.5 on 2019-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191201_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='system',
            field=models.CharField(choices=[('m', 'Metric'), ('i', 'Imperial')], max_length=1, null=True),
        ),
    ]
