# Generated by Django 2.2.5 on 2019-12-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191223_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='picture_filename',
            new_name='profile_filename',
        ),
    ]
