# Generated by Django 2.2.4 on 2020-04-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200310_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_weight_unit',
            field=models.IntegerField(null=True),
        ),
    ]
