# Generated by Django 3.0.5 on 2020-06-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_default_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_distance_unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_speed_unit',
            field=models.IntegerField(null=True),
        ),
    ]
