# Generated by Django 3.0.5 on 2020-09-06 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_follow_approval_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follower_requests',
            field=models.ManyToManyField(blank=True, related_name='user_follower_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
