# Generated by Django 3.0.5 on 2020-09-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_follower_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visibility_profile',
            field=models.CharField(choices=[('e', 'Everyone'), ('r', 'Registered users'), ('f', 'Followers'), ('u', 'Own user')], default='e', max_length=1),
        ),
    ]
