# Generated by Django 3.0.5 on 2020-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_visibility_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_visibility_user_bio_datas',
            field=models.CharField(choices=[('e', 'Everyone'), ('r', 'Registered users'), ('f', 'Followers'), ('u', 'Own user')], default='e', max_length=1),
        ),
    ]
