# Generated by Django 3.0.5 on 2020-09-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_default_visibility_user_bio_datas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='visibility_profile',
            new_name='visibility',
        ),
    ]
