# Generated by Django 3.0.5 on 2020-09-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200924_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_energy_unit',
            field=models.IntegerField(null=True),
        ),
    ]
