# Generated by Django 3.0.5 on 2020-10-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200926_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followings_number',
            field=models.IntegerField(default=0),
        ),
    ]
