# Generated by Django 3.0.5 on 2020-10-16 21:54

from django.db import migrations

def add_follower_and_following_number(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')

    for user in CustomUser.objects.all():
        user.followers_number = user.followers.count()
        user.followings_number = user.following.count()

        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201016_2154'),
    ]

    operations = [
        migrations.RunPython(add_follower_and_following_number),
    ]
