# Generated by Django 3.0.5 on 2021-01-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201016_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tier',
            field=models.CharField(choices=[('n', 'Novice'), ('i', 'Intermediate'), ('a', 'Advanced')], default='n', max_length=1),
            preserve_default=False,
        ),
    ]
