# Generated by Django 3.0.5 on 2021-01-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210109_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_class',
            field=models.BooleanField(default=False),
        ),
    ]
