# Generated by Django 3.0.5 on 2021-01-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_customuser_primary_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
