# Generated by Django 3.0.5 on 2021-01-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210110_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='experience',
        ),
    ]
