# Generated by Django 3.0.5 on 2021-01-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_customuser_experience_next_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primary_class_computed',
            field=models.CharField(default='Athlete', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secondary_class_computed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
