# Generated by Django 3.0.5 on 2021-02-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210112_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
