# Generated by Django 3.0.5 on 2021-02-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_customuser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
