# Generated by Django 3.0.5 on 2021-02-20 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_customuser_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
