# Generated by Django 3.0.5 on 2021-04-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
    ]
