# Generated by Django 3.0.5 on 2021-04-29 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='user_blocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
