# Generated by Django 3.0.5 on 2021-04-29 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_customuser_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='user_blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
