# Generated by Django 3.0.5 on 2022-07-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_customuser_blocked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='system',
            field=models.CharField(choices=[('m', 'Metric'), ('i', 'Imperial')], max_length=1, default='m'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_weight_unit',
            field=models.IntegerField(default=1)
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_distance_unit',
            field=models.IntegerField(default=5)
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_speed_unit',
            field=models.IntegerField(default=11)
        ),
    ]

